# Generated by Django 4.2 on 2024-04-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_carrito_itemcarrito_carrito_flanes_carrito_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='flanes',
        ),
    ]
